### ISSUE TITLE
Boats and Item Frames dont render correctly

### ISSUE THREAD

**Issue by marchofiron** [grondag/canvas#130]
![2020-11-12_19 07 08](https://user-images.githubusercontent.com/74202088/98991646-6f3d2900-252c-11eb-99a4-66935b20995e.png)

![2020-11-12_21 16 48](https://user-images.githubusercontent.com/74202088/98991681-7c5a1800-252c-11eb-94a8-1d9135b36590.png)

(The item frame doesnt render correctly at certain angles.)

**Comment by eristhea** [comment]
The boats were fixed in https://github.com/grondag/canvas/commit/caa93944a3f6a6c2bb819f08053f876263ee32db
Use the latest release from Github

**Comment by marchofiron** [comment]
frames?

**Comment by eristhea** [comment]
not sure about those, you can check yourself.

**Comment by grondag** [comment]
Item frames still don't render correctly when banners and probably some other blocks/entities are in the scene.  Will leave this open until the frames issue is resolved.

**Comment by grondag** [comment]
Item frames should be good now
